ROM registry.cn-shenzhen.aliyuncs.com/yixiao_cloudeon/hadoop:3.3.4

ENV FLINK_HOME=/opt/flink
ENV FLINK_VERSION=1.15.4
ENV PATH=$PATH:$FLINK_HOME/bin

WORKDIR /tmp

RUN wget https://mirrors.huaweicloud.com/apache/flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-scala_2.12.tgz \
    && tar -zxvf flink-*.tgz -C /opt \
    && rm -f flink-*.tgz && mv /opt/flink-*  ${FLINK_HOME}

WORKDIR $FLINK_HOME

