FROM registry.cn-shenzhen.aliyuncs.com/yixiao_cloudeon/rockylinux:9

LABEL baseos=rockylinux9

ENV SUPERSET_VERSION=1.20.1
ENV SUPERSET_HOME=/opt/superset
ENV MINICONDA3_HOME=/opt/miniconda3
ENV TZ=Asia/Shanghai
ENV FREEMARKER_GENERATOR_CLI_HOME=/opt/freemarker-generator-cli
ENV JAVA_HOME=/usr/lib/jvm/java-17/
ENV PATH=$PATH:$JAVA_HOME/bin:$FREEMARKER_GENERATOR_CLI_HOME/bin

ADD freemarker-generator-cli-0.2.0-SNAPSHOT-app.tar.gz /opt/

RUN sed -e 's|^mirrorlist=|#mirrorlist=|g' \
        -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.aliyun.com/rockylinux|g' \
        -i.bak \
        /etc/yum.repos.d/rocky*.repo \
    && mv /opt/freemarker-generator-cli-* /opt/freemarker-generator-cli \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone \
    # 安装 cron、nc、ps 等命令
    && dnf install -y cronie \
    && dnf install -y nmap \
    && dnf install -y procps \
    # 安装JDK
    && dnf install java-17-openjdk-devel -y \
    && dnf install -y wget vim \
    # 安装miniconda
    && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh\
    && sh /miniconda.sh -b -p $MINICONDA3_HOME \
    # 清理安装脚本
    && rm -rf /miniconda.sh \
    # 将 conda 添加到 PATH
    && echo "export PATH=$MINICONDA3_HOME/bin:$PATH" >> /etc/profile \
    && echo "export PATH=$MINICONDA3_HOME/bin:$PATH" >> ~/.bashrc \
    # 配置 conda 国内镜像
    && $MINICONDA3_HOME/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free \
    && $MINICONDA3_HOME/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main \
    && $MINICONDA3_HOME/bin/conda config --set show_channel_urls yes \
    #  创建 Superset 的Python环境
    && $MINICONDA3_HOME/bin/conda create --name superset python=3.10.18 -y \
    #  安装Superset所需依赖
    && dnf install -y gcc gcc-c++ libffi-devel python-devel python-pip python-setuptools openssl-devel cyrus-sasl-devel openldap-devel pkg-config \
    # 安装 MySQL 开发包-需要先启动mysql或mariadb默认，否则下载安装会提示找不到包
    && dnf module enable mariadb -y \
    && dnf install -y mariadb-devel mysql \
    # 更新 pip
    && $MINICONDA3_HOME/envs/superset/bin/pip install --upgrade pip -i https://pypi.douban.com/simple/ \
    # 安装Superset
    && $MINICONDA3_HOME/envs/superset/bin/pip install "apache-superset==4.1.2" -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && ln -s $MINICONDA3_HOME/envs/superset /opt/superset \
    # 生成SECRET_KEY并修改配置SECRET_KEY
    && SECRET_KEY=$(openssl rand -base64 42) \
    && sed -i "s|SECRET_KEY = os.environ.get(\"SUPERSET_SECRET_KEY\") or CHANGE_ME_SECRET_KEY|SECRET_KEY = '${SECRET_KEY}'|" $MINICONDA3_HOME/envs/superset/lib/python3.10/site-packages/superset/config.py \
    # 汉化操作
    && sed -i 's/BABEL_DEFAULT_LOCALE = "en"/BABEL_DEFAULT_LOCALE = "zh"/' $MINICONDA3_HOME/envs/superset/lib/python3.10/site-packages/superset/config.py \
    # 安装python msyql驱动
    && $MINICONDA3_HOME/envs/superset/bin/pip install mysqlclient -i https://pypi.tuna.tsinghua.edu.cn/simple \
    # 修复superset db upgrade初始化Supetset数据库提示：TypeError: Field.init() got an unexpected keyword argument 'minLength'
    && $MINICONDA3_HOME/envs/superset/bin/pip install marshmallow==3.26.1 -i https://pypi.tuna.tsinghua.edu.cn/simple \
    # 修复运行`superset init`初始化角色和权限时提示：INFO:superset.utils.screenshots:No PIL installation found
    && $MINICONDA3_HOME/envs/superset/bin/pip install pillow -i https://pypi.tuna.tsinghua.edu.cn/simple \
    # 安装gunicorn-gunicorn是一个Python Web Server，可以和java中的TomCat类比
    && $MINICONDA3_HOME/envs/superset/bin/pip install gunicorn -i https://pypi.tuna.tsinghua.edu.cn/simple \
    # 下载安装相关数据源
    && $MINICONDA3_HOME/envs/superset/bin/pip install pydoris clickhouse-connect elasticsearch-dbapi starrocks pyhive -i https://pypi.tuna.tsinghua.edu.cn/simple \
    # 清理本地和下载的 rpm 安装包
    && dnf clean all

WORKDIR $SUPERSET_HOME