apiVersion: v1
kind: ConfigMap
metadata:
  name: global-copy-filebeat-config
  labels:
    app: global
data:
  bootstrap.sh: |
    #!/bin/bash
    set -e
    mkdir -p /workspace/filebeat/modules
    mkdir -p /workspace/filebeat/inputs
    chmod 777 /workspace/filebeat
    
    shopt -s nullglob
    files=(/opt/service-common/*filebeat.input.yml)
    if [ ${#files[@]} -gt 0 ]; then
        cp -f "${files[@]}" /workspace/filebeat/inputs/
    fi
    files=(/opt/service-common/*filebeat.module.yml)
    if [ ${#files[@]} -gt 0 ]; then
        cp -f "${files[@]}" /workspace/filebeat/modules/
    fi
    files=(/opt/service-render/*filebeat.input.yml)
    if [ ${#files[@]} -gt 0 ]; then
        cp -f "${files[@]}" /workspace/filebeat/inputs/
    fi
    files=(/opt/service-render/*filebeat.module.yml)
    if [ ${#files[@]} -gt 0 ]; then
        cp -f "${files[@]}" /workspace/filebeat/modules/
    fi
    shopt -u nullglob

    
