site_name: CloudEon Documentation
site_description: 构建于kubernetes集群之上的大数据集群管理平台
site_url: https://github.com/dromara/CloudEon
site_author: Pandas886
repo_name: dromara/CloudEon
repo_url: https://github.com/dromara/CloudEon
edit_uri: ""
extra:
  generator: false
  homepage: https://cloudeon.top
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://github.com/Pandas886
    - icon: fontawesome/brands/github
      link: https://github.com/Pandas886

copyright: Copyright &copy; 2023 CloudEon
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  custom_dir: overrides
  name: material
  language: zh
  logo: images/logo.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep orange
    accent: deep orange
    # - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
        
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link
    - navigation.top
#    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest


nav:
  - index.md
  - mind.md
  - 安装部署:
      - 安装部署/install_pre.md
      - 安装部署/docker.md
      - 安装部署/local.md
  - quickstart.md
  - 组件说明:
      - 组件说明/0.override.md
      - 组件说明/1.global.md
      - 组件说明/2.helm-controller.md
      - 组件说明/3.kube-prometheus.md
      - 组件说明/5.elasticsearch.md
      - 组件说明/6.filebeat.md
      - 组件说明/7.zookeeper.md
      - 组件说明/8.hdfs.md
      - 组件说明/9.yarn.md
      - 组件说明/10.flink.md
  - 组件开发:
      - 组件开发/override.md
      - 组件开发/flow.md
      - 组件开发/volumes.md
      - 组件开发/render_var.md
#  - component_extension.md
  - 社区贡献:
      - 社区贡献/communicate.md
      - 社区贡献/contribute.md
      - 社区贡献/develop.md
      - 社区贡献/windows-develop.md
  - sponsor.md
  - FAQ.md
  - Roadmap.md
