FROM registry.cn-shenzhen.aliyuncs.com/yixiao_cloudeon/rockylinux:9

# 设置环境变量
# 设置环境变量
ENV DATAX_HOME="/opt/datax"
ENV JAVA_HOME=/opt/jdk-11.0.24
ENV MYSQL_CLIENT_HOME=/opt/mysql-shell-8.4.4-linux-glibc2.28-x86-64bit
ENV PATH=$PATH:$JAVA_HOME/bin:$MYSQL_CLIENT_HOME/bin \
    LD_LIBRARY_PATH=$JAVA_HOME/lib/amd64/jli:$JAVA_HOME/lib/amd64

# 使用 ADD 自动解压 datax.tar.gz
ADD datax.tar.gz \
    jdk-11.0.24_linux-x64_bin.tar.gz \
    mysql-community-client-8.4.4-el9.x86_64.tar.gz  /opt/

RUN mv /opt/datax-web-* $DATAX_WEB_HOME

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone \
    # 安装 MySQL 官方客户端命令（相比 MySQL Shell，磁盘空间占用小） \
    && dnf install -y /opt/mysql-community-client-plugins-8.4.4-1.el9.x86_64.rpm \
    && dnf install -y /opt/mysql-community-common-8.4.4-1.el9.x86_64.rpm \
    && dnf install -y /opt/mysql-community-libs-8.4.4-1.el9.x86_64.rpm \
    && dnf install -y /opt/mysql-community-client-8.4.4-1.el9.x86_64.rpm \
    # 安装 cron、nc、ps 等命令
    && dnf install -y cronie \
    && dnf install -y nmap \
    && dnf install -y procps \
    # 清理本地和下载的 rpm 安装包
    && rm -fv /opt/mysql-community-*.rpm \
    && dnf clean all

# 执行安装脚本并验证安装结果
RUN chmod +x $DATAX_WEB_HOME/bin/install.sh && \
    { echo "y"; } | $DATAX_WEB_HOME/bin/install.sh --force && \
    # 验证安装结果
    test -d "$DATAX_WEB_HOME/modules" || { echo "Installation failed: modules directory not created"; exit 1; }

# 暴露端口
EXPOSE 8080 9999

# 设置工作目录
WORKDIR $DATAX_HOME
WORKDIR $DATAX_WEB_HOME